runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.php
- url: /deleteTweets
  script: deleteTweets.php

env_variables:
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: 127.0.0.1
  DB_DATABASE: retrievetweets
  DB_USERNAME: root
  DB_PASSWORD: 27051993Hang
  DB_SOCKET: #"/cloudsql/project:region:cloudsql-instance"

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: #"project:region:cloudsql-instance"